spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cookalone?serverTimezone=UTC&characterEncoding=UTF-8
    username: serberos
    password: cookalone1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

  #OAuth | 해당 profile 정보를 가져온다. (application-xxx.properties로 만들면 xxx라는 profile이 생성되어 관리 할 수 있다.)
  profiles:
    include: oauth

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace